---
apiVersion: v1
kind: ConfigMap
data:
  # You can add multiple configuration files here to use a multi-cluster setup
  vitastor.conf: |-
    {"etcd_address":"http://192.168.7.2:2379","etcd_prefix":"/vitastor"}
metadata:
  namespace: vitastor-system
  name: vitastor-config
