---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vitastor-system
  name: vitastor-csi-nodeplugin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: vitastor-system
  name: vitastor-csi-nodeplugin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
  # allow to read Vault Token and connection options from the Tenants namespace
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: vitastor-system
  name: vitastor-csi-nodeplugin
subjects:
  - kind: ServiceAccount
    name: vitastor-csi-nodeplugin
    namespace: vitastor-system
roleRef:
  kind: ClusterRole
  name: vitastor-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
