---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vitastor-pvc
spec:
  storageClassName: vitastor-csi-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
