---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vitastor-clone
spec:
  storageClassName: vitastor
  dataSource:
    name: snap1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
